name: golangci-lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.5'
    - name: Test
      run: |
        cd company-service
        go test -v ./...
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [company-service, user-service]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 1.22.5
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.59
        working-directory: ${{ matrix.directory }}